version: '3.8'

services:
  db:
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MQSQL_DATABASE=ad
      - MYSQL_USER=root
    ports:
      - 3306:3306
    volumes:
      - ./ad-microservice/db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
  ad-app:
    build: ./ad-microservice
    container_name: ad-app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run start
volumes:
  db: