version: '3.8'

services:
  db:
    image: mysql:8.0.28
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MYSQL_USER=root
    volumes:
      - db:/var/lib/mysql
  app_ad:
    build: ./ad-microservice
    container_name: app_ad
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run start
  app_registration:
    build: ./register-microservice
    container_name: app_registration
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: npm run start
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - '/frontend/node_modules'
    ports:
      - 3004:3004
volumes:
  db:
