version: '3.8'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw
      - MQSQL_DATABASE=ad
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  ad-app:
    depends_on:
      - db
    build: ./
    container_name: ad-app
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: sh deploy.sh
volumes:
  db: